// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"product_service/internal/api"
	"product_service/internal/api/handler"
	"product_service/internal/config"
	"product_service/internal/db"
	"product_service/internal/repository"
	"product_service/internal/service"
)

// Injectors from wire.go:

func Initialize(cfg config.Config) (*http.Server, error) {
	sqlxDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	err = db.Migrate(sqlxDB)
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepository(sqlxDB)
	productService := service.NewProductService(productRepository)
	productHandler := handler.NewProductHandler(productService)
	server := http.NewServer(productHandler)
	return server, nil
}
